// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ArticleHandle : RemoteTableHandle<EventContext, Article>
        {
            protected override string RemoteTableName => "article";

            public sealed class ArticleIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Article row) => row.ArticleId;

                public ArticleIdUniqueIndex(ArticleHandle table) : base(table) { }
            }

            public readonly ArticleIdUniqueIndex ArticleId;

            internal ArticleHandle(DbConnection conn) : base(conn)
            {
                ArticleId = new(this);
            }

            protected override object GetPrimaryKey(Article row) => row.ArticleId;
        }

        public readonly ArticleHandle Article;
    }
}
