// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DepositHandle : RemoteTableHandle<EventContext, Deposit>
        {
            protected override string RemoteTableName => "deposit";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Deposit row) => row.Id;

                public IdUniqueIndex(DepositHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal DepositHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Deposit row) => row.Id;
        }

        public readonly DepositHandle Deposit;
    }
}
