// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PackageHandle : RemoteTableHandle<EventContext, Package>
        {
            protected override string RemoteTableName => "package";

            public sealed class IdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Package row) => row.Id;

                public IdUniqueIndex(PackageHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PackageHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Package row) => row.Id;
        }

        public readonly PackageHandle Package;
    }
}
