// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TransportLogHandle : RemoteTableHandle<EventContext, TransportLog>
        {
            protected override string RemoteTableName => "transport_log";

            public sealed class LogIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(TransportLog row) => row.LogId;

                public LogIdUniqueIndex(TransportLogHandle table) : base(table) { }
            }

            public readonly LogIdUniqueIndex LogId;

            internal TransportLogHandle(DbConnection conn) : base(conn)
            {
                LogId = new(this);
            }

            protected override object GetPrimaryKey(TransportLog row) => row.LogId;
        }

        public readonly TransportLogHandle TransportLog;
    }
}
