// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdvancePackageStateHandler(ReducerEventContext ctx, string packageId, string newState);
        public event AdvancePackageStateHandler? OnAdvancePackageState;

        public void AdvancePackageState(string packageId, string newState)
        {
            conn.InternalCallReducer(new Reducer.AdvancePackageState(packageId, newState), this.SetCallReducerFlags.AdvancePackageStateFlags);
        }

        public bool InvokeAdvancePackageState(ReducerEventContext ctx, Reducer.AdvancePackageState args)
        {
            if (OnAdvancePackageState == null) return false;
            OnAdvancePackageState(
                ctx,
                args.PackageId,
                args.NewState
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdvancePackageState : Reducer, IReducerArgs
        {
            [DataMember(Name = "packageId")]
            public string PackageId;
            [DataMember(Name = "newState")]
            public string NewState;

            public AdvancePackageState(
                string PackageId,
                string NewState
            )
            {
                this.PackageId = PackageId;
                this.NewState = NewState;
            }

            public AdvancePackageState()
            {
                this.PackageId = "";
                this.NewState = "";
            }

            string IReducerArgs.ReducerName => "AdvancePackageState";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdvancePackageStateFlags;
        public void AdvancePackageState(CallReducerFlags flags) => AdvancePackageStateFlags = flags;
    }
}
