// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateTravelOrderHandler(ReducerEventContext ctx, uint sourceDepotId, uint destDepotId);
        public event CreateTravelOrderHandler? OnCreateTravelOrder;

        public void CreateTravelOrder(uint sourceDepotId, uint destDepotId)
        {
            conn.InternalCallReducer(new Reducer.CreateTravelOrder(sourceDepotId, destDepotId), this.SetCallReducerFlags.CreateTravelOrderFlags);
        }

        public bool InvokeCreateTravelOrder(ReducerEventContext ctx, Reducer.CreateTravelOrder args)
        {
            if (OnCreateTravelOrder == null) return false;
            OnCreateTravelOrder(
                ctx,
                args.SourceDepotId,
                args.DestDepotId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateTravelOrder : Reducer, IReducerArgs
        {
            [DataMember(Name = "sourceDepotId")]
            public uint SourceDepotId;
            [DataMember(Name = "destDepotId")]
            public uint DestDepotId;

            public CreateTravelOrder(
                uint SourceDepotId,
                uint DestDepotId
            )
            {
                this.SourceDepotId = SourceDepotId;
                this.DestDepotId = DestDepotId;
            }

            public CreateTravelOrder()
            {
            }

            string IReducerArgs.ReducerName => "CreateTravelOrder";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateTravelOrderFlags;
        public void CreateTravelOrder(CallReducerFlags flags) => CreateTravelOrderFlags = flags;
    }
}
