// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateArticleStatusHandler(ReducerEventContext ctx, string articleId, string newStatus);
        public event UpdateArticleStatusHandler? OnUpdateArticleStatus;

        public void UpdateArticleStatus(string articleId, string newStatus)
        {
            conn.InternalCallReducer(new Reducer.UpdateArticleStatus(articleId, newStatus), this.SetCallReducerFlags.UpdateArticleStatusFlags);
        }

        public bool InvokeUpdateArticleStatus(ReducerEventContext ctx, Reducer.UpdateArticleStatus args)
        {
            if (OnUpdateArticleStatus == null) return false;
            OnUpdateArticleStatus(
                ctx,
                args.ArticleId,
                args.NewStatus
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateArticleStatus : Reducer, IReducerArgs
        {
            [DataMember(Name = "articleId")]
            public string ArticleId;
            [DataMember(Name = "newStatus")]
            public string NewStatus;

            public UpdateArticleStatus(
                string ArticleId,
                string NewStatus
            )
            {
                this.ArticleId = ArticleId;
                this.NewStatus = NewStatus;
            }

            public UpdateArticleStatus()
            {
                this.ArticleId = "";
                this.NewStatus = "";
            }

            string IReducerArgs.ReducerName => "UpdateArticleStatus";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateArticleStatusFlags;
        public void UpdateArticleStatus(CallReducerFlags flags) => UpdateArticleStatusFlags = flags;
    }
}
