// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type TransportLog = {
  logId: number,
  packageId: string,
  fromDeposit: number,
  toDeposit: number,
  createdTime: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace TransportLog {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("logId", AlgebraicType.createU32Type()),
      new ProductTypeElement("packageId", AlgebraicType.createStringType()),
      new ProductTypeElement("fromDeposit", AlgebraicType.createU32Type()),
      new ProductTypeElement("toDeposit", AlgebraicType.createU32Type()),
      new ProductTypeElement("createdTime", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: TransportLog): void {
    TransportLog.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): TransportLog {
    return TransportLog.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


