// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Article
    {
        [DataMember(Name = "ArticleId")]
        public string ArticleId;
        [DataMember(Name = "CurrentDeposit")]
        public uint CurrentDeposit;
        [DataMember(Name = "Status")]
        public string Status;

        public Article(
            string ArticleId,
            uint CurrentDeposit,
            string Status
        )
        {
            this.ArticleId = ArticleId;
            this.CurrentDeposit = CurrentDeposit;
            this.Status = Status;
        }

        public Article()
        {
            this.ArticleId = "";
            this.Status = "";
        }
    }
}
