// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Deposit
    {
        [DataMember(Name = "Id")]
        public uint Id;
        [DataMember(Name = "Name")]
        public string Name;
        [DataMember(Name = "PackagesOnSite")]
        public System.Collections.Generic.List<string> PackagesOnSite;
        [DataMember(Name = "OutgoingPackageIds")]
        public System.Collections.Generic.List<string> OutgoingPackageIds;

        public Deposit(
            uint Id,
            string Name,
            System.Collections.Generic.List<string> PackagesOnSite,
            System.Collections.Generic.List<string> OutgoingPackageIds
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.PackagesOnSite = PackagesOnSite;
            this.OutgoingPackageIds = OutgoingPackageIds;
        }

        public Deposit()
        {
            this.Name = "";
            this.PackagesOnSite = new();
            this.OutgoingPackageIds = new();
        }
    }
}
