// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Package
    {
        [DataMember(Name = "Id")]
        public string Id;
        [DataMember(Name = "MaxLoad")]
        public uint MaxLoad;
        [DataMember(Name = "Contents")]
        public System.Collections.Generic.List<string> Contents;
        [DataMember(Name = "State")]
        public string State;
        [DataMember(Name = "SourceDeposit")]
        public uint SourceDeposit;
        [DataMember(Name = "DestinationDeposit")]
        public uint DestinationDeposit;

        public Package(
            string Id,
            uint MaxLoad,
            System.Collections.Generic.List<string> Contents,
            string State,
            uint SourceDeposit,
            uint DestinationDeposit
        )
        {
            this.Id = Id;
            this.MaxLoad = MaxLoad;
            this.Contents = Contents;
            this.State = State;
            this.SourceDeposit = SourceDeposit;
            this.DestinationDeposit = DestinationDeposit;
        }

        public Package()
        {
            this.Id = "";
            this.Contents = new();
            this.State = "";
        }
    }
}
