// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TransportLog
    {
        [DataMember(Name = "LogId")]
        public uint LogId;
        [DataMember(Name = "PackageId")]
        public string PackageId;
        [DataMember(Name = "FromDeposit")]
        public uint FromDeposit;
        [DataMember(Name = "ToDeposit")]
        public uint ToDeposit;
        [DataMember(Name = "CreatedTime")]
        public SpacetimeDB.Timestamp CreatedTime;

        public TransportLog(
            uint LogId,
            string PackageId,
            uint FromDeposit,
            uint ToDeposit,
            SpacetimeDB.Timestamp CreatedTime
        )
        {
            this.LogId = LogId;
            this.PackageId = PackageId;
            this.FromDeposit = FromDeposit;
            this.ToDeposit = ToDeposit;
            this.CreatedTime = CreatedTime;
        }

        public TransportLog()
        {
            this.PackageId = "";
        }
    }
}
